// ISO 3166-1 alpha-2 country codes with common names (sorted by name)
export const COUNTRIES: { code: string; name: string }[] = [
  { code: "TR", name: "Türkiye" },
  { code: "DE", name: "Almanya" },
  { code: "AT", name: "Avusturya" },
  { code: "BE", name: "Belçika" },
  { code: "BG", name: "Bulgaristan" },
  { code: "CZ", name: "Çekya" },
  { code: "CN", name: "Çin" },
  { code: "DK", name: "Danimarka" },
  { code: "AE", name: "Birleşik Arap Emirlikleri" },
  { code: "GB", name: "Birleşik Krallık" },
  { code: "US", name: "Amerika Birleşik Devletleri" },
  { code: "FI", name: "Finlandiya" },
  { code: "FR", name: "Fransa" },
  { code: "NL", name: "Hollanda" },
  { code: "GR", name: "Yunanistan" },
  { code: "HR", name: "Hırvatistan" },
  { code: "IN", name: "Hindistan" },
  { code: "IE", name: "İrlanda" },
  { code: "ES", name: "İspanya" },
  { code: "SE", name: "İsveç" },
  { code: "CH", name: "İsviçre" },
  { code: "IT", name: "İtalya" },
  { code: "JP", name: "Japonya" },
  { code: "CA", name: "Kanada" },
  { code: "PL", name: "Polonya" },
  { code: "PT", name: "Portekiz" },
  { code: "RO", name: "Romanya" },
  { code: "RU", name: "Rusya" },
  { code: "SA", name: "Suudi Arabistan" },
  { code: "UA", name: "Ukrayna" },
  { code: "HU", name: "Macaristan" },
  { code: "NO", name: "Norveç" },
  { code: "AU", name: "Avustralya" },
  { code: "AZ", name: "Azerbaycan" },
  { code: "BY", name: "Belarus" },
  { code: "BR", name: "Brezilya" },
  { code: "EG", name: "Mısır" },
  { code: "EE", name: "Estonya" },
  { code: "GE", name: "Gürcistan" },
  { code: "HK", name: "Hong Kong" },
  { code: "ID", name: "Endonezya" },
  { code: "IL", name: "İsrail" },
  { code: "KZ", name: "Kazakistan" },
  { code: "KW", name: "Kuveyt" },
  { code: "LV", name: "Letonya" },
  { code: "LT", name: "Litvanya" },
  { code: "MY", name: "Malezya" },
  { code: "MX", name: "Meksika" },
  { code: "QA", name: "Katar" },
  { code: "SG", name: "Singapur" },
  { code: "SK", name: "Slovakya" },
  { code: "SI", name: "Slovenya" },
  { code: "ZA", name: "Güney Afrika" },
  { code: "KR", name: "Güney Kore" },
  { code: "TH", name: "Tayland" },
  { code: "TN", name: "Tunus" },
  { code: "UZ", name: "Özbekistan" },
  { code: "VN", name: "Vietnam" },
  { code: "BA", name: "Bosna-Hersek" },
  { code: "CY", name: "Kıbrıs" },
  { code: "IS", name: "İzlanda" },
  { code: "LU", name: "Lüksemburg" },
  { code: "NZ", name: "Yeni Zelanda" },
  { code: "RS", name: "Sırbistan" },
].sort((a, b) => a.name.localeCompare(b.name, "tr"))

export function getCountryName(code: string): string {
  const c = COUNTRIES.find((x) => x.code === code || x.name.toLowerCase() === code.toLowerCase())
  if (c) return c.name
  const typos: Record<string, string> = { ukrain: "Ukrayna", turkiye: "Türkiye", turkey: "Türkiye" }
  return typos[code.toLowerCase()] ?? code
}
